name: Print Env

on: push

jobs: 
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "actions: ${GITHUB_ACTIONS}"
          echo "actor: ${GITHUB_ACTOR}""
          echo "ref: ${GITHUB_SHA}"
          echo "ref: ${GITHUB_REF}"